apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: face-attendance
resources:
  - namespace.yaml
  - api-gateway/deployment.yaml
  - auth-service/deployment.yaml
  - student-service/deployment.yaml
  - attendance-service/deployment.yaml
  - face-recognition-service/deployment.yaml
  - observability/servicemonitor.yaml

