apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: face-attendance-services
spec:
  selector:
    matchExpressions:
      - key: app
        operator: Exists
  endpoints:
    - port: http
      path: /metrics
      interval: 30s

